# Generated by Django 3.2.9 on 2021-11-04 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'Admin'), (2, 'Manager'), (3, 'Super Manager'), (4, 'Inventory Clerk'), (5, ' Super admin'), (6, 'Technician')], primary_key=True, serialize=False)),
            ],
        ),
    ]
