# Generated by Django 3.2.9 on 2021-11-04 02:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maincategories', '0001_initial'),
        ('subcategories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('authorize', models.BooleanField(default=False)),
                ('type', models.PositiveBigIntegerField(choices=[(1, 'TOOL'), (2, 'CONSUMABLE'), (3, 'TOOLKIT')], default=1)),
                ('code', models.CharField(max_length=100)),
                ('serial', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('updated_by', models.CharField(max_length=100, null=True)),
                ('created_at', models.CharField(max_length=100)),
                ('updated_at', models.CharField(max_length=100, null=True)),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maincategories.maincategory')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subcategories.subcategory')),
            ],
        ),
    ]
