# Generated by Django 3.2.9 on 2021-11-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_item_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default='Name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='o_quantity',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(default='PENDING', max_length=100),
        ),
    ]
