# Generated by Django 3.2.9 on 2021-11-04 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_auto_20211104_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='updated_at',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
