# Generated by Django 3.2.9 on 2021-11-04 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0003_auto_20211104_0812'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('toolstates', '0002_itemstate_is_deleted'),
        ('vendors', '0002_vendor_is_deleted'),
        ('location', '0002_location_is_deleted'),
        ('warehouses', '0003_warehouse_is_deleted'),
        ('item', '0002_item_is_deleted'),
        ('toolbrand', '0002_itembrand_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('officer', models.CharField(max_length=100)),
                ('memo', models.CharField(max_length=100)),
                ('vehicle', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('source_bin', models.CharField(max_length=100)),
                ('invoice', models.CharField(max_length=100)),
                ('lpo', models.CharField(max_length=100, null=True)),
                ('document', models.CharField(max_length=100, null=True)),
                ('delivery_note_number', models.CharField(max_length=100, null=True)),
                ('item_qty', models.IntegerField(default=0)),
                ('cost_per_tool', models.IntegerField(default=0)),
                ('price_per_tool', models.IntegerField(default=0)),
                ('start_milleage', models.CharField(max_length=100)),
                ('stop_milleage', models.CharField(max_length=100)),
                ('callibration', models.CharField(max_length=100)),
                ('warranty', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('serial', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
                ('brands', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toolbrand.itembrand')),
                ('brought_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.item')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.location')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('states', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toolstates.itemstate')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouses.warehouse')),
            ],
        ),
    ]
