# Generated by Django 3.2.9 on 2021-11-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0003_warehouse_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
