# Generated by Django 3.2.9 on 2021-11-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0004_alter_warehouse_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='status',
            field=models.CharField(default='PENDING', max_length=100),
        ),
    ]
